### PR TITLE
Update source to 2022.06.15

### PR DESCRIPTION
**Pull request by psmedley**
Signed-off-by: Paul Smedley <paul@smedley.id.au>

### CODE REVIEW

**Comment by dmik** [comment]
Paul, thanks for bringing this up, although the vendor merge policy is different here (to have a more clear history) so I did it differently (via the vendor branch in 5bd02bcbb784ce4a38c1d643837ef98dd605074d). Now it's time to merge into main and try to build. There might be issues because support for Qt 5.x was officially 'dropped" by the author in April, see https://github.com/textbrowser/dooble/commit/8a5cef0c2aa8bb6f32686e482857d109eb25111c. This should be back portable to Qt5 though.

BTW, the merge policy we use for many projects (including Qt and Dooble) is described in detail here: https://github.com/bitwiseworks/qt5-os2/wiki/Developers, JFYI.

**Comment by StevenLevine** [comment]
The merge policy defined in "Importing a new version of a Qt module to an OS/2 repository" works fine for developers with commit access to the repo.  To my way of thinking something needs to be added discussing how to integrate the existing policy with pull requests.  As I see it once the vendor branch is updated, the pull request only needs to include commits to the main branch to fix merge errors.  The other steps will stay the same.

If so, what needs to be added is a discussion of how to request a vendor branch update.  Once the vendor branch is updated the rest of the work can be done in the forked repo until the pull request is ready to be submitted.  Opening a task ticket requesting the vendor branch update will probably get the job done.

**Comment by dmik** [comment]
No-no, It has nothing to do with the access rights. It can all be done locally and pushed as a merge request across the `vendor` branch instead of `main`. The described technique is essentially a way to "squash" all upstream history between merge points into a single commit and not miss a single bit. It's very precise and will import all operations including file renames and deletes yet keeping the history clean. This is why it's better than doing anything else. If Paul (or whoever does that) can guarantee that they squashed everything as described — what will be enough.

And then next step (after accepting such a push request on `vendor`) will be to merge `vendor` to `main`, fix conflicts and build failures etc. But I don't think it's possible to do this within the same push request as they don't seem to interoperate between different branches. After all, merge requests are simply not designed for such complex operations like upstream updates. They are designed for fixes, adding new features, etc.

**Comment by StevenLevine** [comment]
I see. Until now, I never had the need for a merge request and had not accidentally learned that they existed.  It makes sense that they should.  Thanks.

**Pull request closed without merging**
